### ISSUE TITLE
which brand of keyboard could press perfect?

### ISSUE THREAD

**Issue by angus006** [patrikzudel/strafe-evaluation#10]
i use filco  keybord  for many years，red axis，
but i can't perfect strafe, always too early or too late.

**Comment by patrikzudel** [comment]
I've seen people get perfect strafes on a lot of different keyboards, probably it is easier with Rapid Trigger but it should be doable on most decent gaming keyboards. **It is not easy though.** 

Frankly I've gotten perfect strafes on a random wireless keyboard from Microsoft so it could be a skill issue 😄

**Comment by angus006** [comment]
many thanks for your reply
