### ISSUE TITLE
Error: Downloading WebView2 Failed

### ISSUE THREAD

**Issue by aethersphere** [patrikzudel/strafe-evaluation#4]
![image](https://github.com/user-attachments/assets/890eb3a8-d8aa-48e9-b1a0-89f990257a8b)
tried restarting the installer, didnt help

**Comment by patrikzudel** [comment]
Try the .msi installer

Do you by any chance use some DNS Level Ad blocker? (Pi-hole etc.)

**Comment by aethersphere** [comment]
Same thing, but different error with msi installer. I dont use any kind of DNS 
![image](https://github.com/user-attachments/assets/d3107123-ad81-49f1-a66d-8c75fbefc506)

**Comment by patrikzudel** [comment]
Try installing WebView2 manually from here - https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download-section

**Comment by aethersphere** [comment]
It works now after manually installing webview2, thanks
